# Generated by Django 4.2.13 on 2024-05-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('lavozimi', models.CharField(max_length=255)),
                ('qabul_kunlari', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(default='media\\default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Standartlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarkibiy_bolinmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('lavozimi', models.CharField(max_length=255)),
                ('qabul_kunlari', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(default='media\\default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Xabarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(default='media\\default.jpg', upload_to='')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
