# Generated by Django 4.2.13 on 2024-05-16 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SHNK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hujjat_raqami', models.IntegerField()),
                ('kalit_soz', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qurilish_reglamentlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('belgilanishi', models.CharField(max_length=55)),
                ('nomi', models.CharField(max_length=255)),
                ('hujjat', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Boglanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('telefon', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('img', models.ImageField(default='media\\default.jpg', upload_to='')),
                ('manzili', models.CharField(max_length=128)),
                ('rahbariyat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='SHNK.rahbariyat')),
            ],
        ),
    ]
