# Generated by Django 4.2.13 on 2024-05-18 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SHNK', '0002_esf_qurilish_reglamentlari_boglanish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('rus', models.TextField(max_length=20)),
                ('uzb', models.TextField(max_length=20)),
                ('turk', models.TextField(max_length=20)),
                ('eng', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SHNKTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_name_uz', models.CharField(max_length=10, unique=True)),
                ('type_name_ru', models.CharField(max_length=10, null=True, unique=True)),
                ('type_description_uz', models.CharField(max_length=255, null=True)),
                ('type_description_ru', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SHNK types',
                'db_table': 'shnk_types',
            },
        ),
        migrations.CreateModel(
            name='SHNKSystemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('system_name_uz', models.CharField(max_length=255, unique=True)),
                ('system_name_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SHNK systems',
                'db_table': 'shnk_systems',
            },
        ),
        migrations.CreateModel(
            name='SHNKGroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(max_length=15)),
                ('group_name_uz', models.CharField(max_length=255)),
                ('group_name_ru', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHNK.shnksystemsmodel')),
            ],
            options={
                'verbose_name_plural': 'SHNK groups',
                'db_table': 'shnk_groups',
            },
        ),
        migrations.CreateModel(
            name='SHNKDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shnk_name_uz', models.CharField(max_length=255, unique=True)),
                ('shnk_name_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('shnk_code', models.CharField(max_length=10)),
                ('shnk_file_uz', models.FileField(blank=True, null=True, upload_to='shnk')),
                ('shnk_file_ru', models.FileField(blank=True, null=True, upload_to='shnk')),
                ('shnk_rating', models.JSONField(default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shnk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHNK.shnkgroupsmodel')),
                ('shnk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHNK.shnktypesmodel')),
            ],
            options={
                'verbose_name_plural': 'SHNK documents',
                'db_table': 'shnk_documents',
            },
        ),
    ]
